Use `docker_client` to create a Docker handle in validation function
The recently introduced `docker_client` function can be used to obtain a
Docker handle, and also contains dedicated checks and diagnostics for
the case that no Docker daemon is running.

This patch updates `_validate_docker_network` to use `docker_client`
instead of directly interacting with the Docker API with
`docker.from_env`. While `docker_client` raises exceptions `click` can
display (and which contain user-relevant information), `docker.from_env`
raises raw, low-level exceptions which are not handled by `click` and
are propagated to the user as is.

With this patch and no Docker daemon running users are presented with
the following error message:

    $ dcos-docker create  dcos_generate_config.sh
    Error: Cannot connect to Docker.
    Make sure that Docker is installed and running, and that you can run "docker ps".
    If "sudo docker ps" works, try following the instructions at https://docs.docker.com/install/linux/linux-postinstall/.

while previously they were faced with and asked to diagnose the
following:

    $ dcos-docker create --agents 1 --license-key dcos.license --variant enterprise --security-mode disabled dcos_generate_config.ee.sh
    Traceback (most recent call last):
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
        self.send(msg)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
        self.connect()
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
        sock.connect(self.unix_socket)
    ConnectionRefusedError: [Errno 61] Connection refused

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
        timeout=timeout
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
        self.send(msg)
      File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
        self.connect()
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
        sock.connect(self.unix_socket)
    urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 175, in _retrieve_server_version
        return self.version(api_version=False)["ApiVersion"]
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/api/daemon.py", line 181, in version
        return self._result(self._get(url), json=True)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
        return f(self, *args, **kwargs)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 198, in _get
        return self.get(url, **self._set_request_timeout(kwargs))
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
        return self.request('GET', url, **kwargs)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/dcos-docker", line 11, in <module>
        load_entry_point('DCOS-E2E==2018.7.25.0', 'console_scripts', 'dcos-docker')()
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/click/core.py", line 1064, in invoke
        sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/click/core.py", line 621, in make_context
        self.parse_args(ctx, args)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/click/core.py", line 880, in parse_args
        value, args = param.handle_parse_result(ctx, opts, args)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/click/core.py", line 1404, in handle_parse_result
        self.callback, ctx, self, value)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/click/core.py", line 78, in invoke_param_callback
        return callback(ctx, param, value)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/cli/dcos_docker/commands/create.py", line 72, in _validate_docker_network
        client = docker.from_env(version='auto')
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/client.py", line 85, in from_env
        timeout=timeout, version=version, **kwargs_from_env(**kwargs)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/client.py", line 40, in __init__
        self.api = APIClient(*args, **kwargs)
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 158, in __init__
        self._version = self._retrieve_server_version()
      File "/usr/local/Cellar/dcose2e/2018.07.25.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 183, in _retrieve_server_version
        'Error while fetching server API version: {0}'.format(e)
    docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))